# Generated by Django 4.1.6 on 2023-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('status', models.CharField(default='new', max_length=10, verbose_name='status')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion time')),
            ],
        ),
    ]
