# Generated by Django 4.1.7 on 2023-02-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('in process', 'In Process')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
