# Generated by Django 4.1.7 on 2023-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_details_alter_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('COMPLETED', 'completed'), ('IN_PROCESS', 'in process')], default='NEW', max_length=20, verbose_name='status'),
        ),
    ]
