# Generated by Django 4.1.7 on 2023-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_completion_date_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('IN_PROCESS', 'in process'), ('COMPLETED', 'completed')], default='NEW', max_length=20, verbose_name='status'),
        ),
    ]
